version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - ls -lrt
      - docker --version
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ankit-repo:latest .
      - docker tag ankit-repo:latest public.ecr.aws/e0a9c7y2/ankit-repo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/e0a9c7y2/ankit-repo
artifacts:
  files:
    - '**/*'
