version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=525660028624.dkr.ecr.us-west-2.amazonaws.com/ankit-repo
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - ls -lrt
      - docker --version
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ankit:latest .
      - docker tag ankit:latest 525660028624.dkr.ecr.us-west-2.amazonaws.com/ankit-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 525660028624.dkr.ecr.us-west-2.amazonaws.com/ankit-repo:latest
      - printf '[{"name":"ankush","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
